- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
> rename dynamic array to sequence

- rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake
- rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
This is for compatibility with uncrustify v0.68.
Connects to ros2/rosidl#340
Connects to ament/uncrustify_vendor#3
> Change uncrustify max line length to 0

- rosidl_typesupport_fastrtps_c/bin/rosidl_typesupport_fastrtps_c
- rosidl_typesupport_fastrtps_cpp/bin/rosidl_typesupport_fastrtps_cpp
> remove usage of UnknownMessageType

- rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/resource/srv__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/srv__rosidl_typesupport_fastrtps_cpp.hpp.em
- rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
> update code to match refactoring of rosidl definitions

- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
> simplify code using updated definition API

- rosidl_typesupport_fastrtps_c/CMakeLists.txt
- rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/wstring_conversion.hpp
- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/src/wstring_conversion.cpp
- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/wstring_conversion.hpp
- rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
- rosidl_typesupport_fastrtps_cpp/src/wstring_conversion.cpp
Connect to ros2/rosidl#352.
While waiting for ros2/rcl_interfaces#58 the patch (without tests) can already be reviewed.
> add WString support

- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
> fix ts for long double and wchar

- rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake
> Remove non-package from ament_target_dependencies()

- rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/resource/srv__rosidl_typesupport_fastrtps_c.h.em
Related to ament/ament_lint#214.
> style update to match uncrustify with explicit language

- rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake
- rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
See https://github.com/ros2/rosidl/pull/453.
> Export typesupport library in a separate cmake variable

- rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/wstring_conversion.hpp
- rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/resource/srv__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/src/wstring_conversion.cpp
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support_decl.hpp
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support_decl.hpp
- rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em
> rename rosidl_generator_c namespace to rosidl_runtime_c

- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/idl__type_support.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em
> update includes to use non-entry point headers from detail subdir

- rosidl_typesupport_fastrtps_c/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
> export targets in a addition to include directories / libraries

- rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
> export targets in addition to include directories / libraries

- fastrtps_cmake_module/QUALITY_DECLARATION.md
- fastrtps_cmake_module/README.md
- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/README.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/README.md
Adding current-level Quality Declarations and READMEs for all three packages in this repo.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Add Quality Declarations and READMEs for each package

- fastrtps_cmake_module/README.md
- rosidl_typesupport_fastrtps_c/Doxyfile
- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/README.md
- rosidl_typesupport_fastrtps_c/docs/FEATURES.md
- rosidl_typesupport_fastrtps_cpp/Doxyfile
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/README.md
- rosidl_typesupport_fastrtps_cpp/docs/FEATURES.md
As part of the push to higher quality levels, this adds feature documentation for these packages.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Feature documentation

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/identifier.h
- rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/wstring_conversion.hpp
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/identifier.hpp
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support_decl.hpp
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support_decl.hpp
- rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/wstring_conversion.hpp
This updates the API documentation of these packages to help bump the documentation category of their Quality Level to 1.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Updating public API documentation

- rosidl_typesupport_fastrtps_c/CMakeLists.txt
- rosidl_typesupport_fastrtps_c/package.xml
- rosidl_typesupport_fastrtps_c/test/test_wstring_conversion.cpp
- rosidl_typesupport_fastrtps_c/test/test_wstring_conversion_mem.cpp
- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/package.xml
- rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion.cpp
- rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion_mem.cpp
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10815)](http://ci.ros2.org/job/ci_linux/10815/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6193)](http://ci.ros2.org/job/ci_linux-aarch64/6193/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=8806)](http://ci.ros2.org/job/ci_osx/8806/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=10702)](http://ci.ros2.org/job/ci_windows/10702/)
> Add tests for wstring conversion routines

- fastrtps_cmake_module/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Update Version Stability to stable version
Signed-off-by: ahcorde <ahcorde@gmail.com>
> QD Update Version Stability to stable version

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
> Bump the Quality Declaration for typesupport_fastrtps_c{pp,} to Level 3.

- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
fix invalid return on `_@(message.structure.namespaced_type.name)__cdr_deserialize` function
- It should return bool type, but returning string
> fix invalid return on deserialize function

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/README.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/README.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Updated QD

- rosidl_typesupport_fastrtps_c/CMakeLists.txt
- rosidl_typesupport_fastrtps_c/package.xml
- rosidl_typesupport_fastrtps_c/test/benchmark/benchmark_string_conversions.cpp
- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/package.xml
- rosidl_typesupport_fastrtps_cpp/test/benchmark/benchmark_string_conversions.cpp
Signed-off-by: ahcorde <ahcorde@gmail.com>
> [Backport Foxy] Added benchmark test to rosidl_typesupport_fastrtps_c/cpp (#52)

- fastrtps_cmake_module/package.xml
- rosidl_typesupport_fastrtps_c/package.xml
- rosidl_typesupport_fastrtps_cpp/package.xml
Precisely what the title says.
> Update package maintainers.

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Signed-off-by: ahcorde <ahcorde@gmail.com>
> Update some missing QL statements to 2

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
> Fix item number in QD

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
> [Foxy backport] Fix item number in QD (#59)

- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Update QDs with up-to-date content

- rosidl_typesupport_fastrtps_c/bin/rosidl_typesupport_fastrtps_c
- rosidl_typesupport_fastrtps_c/package.xml
- rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/__init__.py
- rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/cli.py
- rosidl_typesupport_fastrtps_c/setup.cfg
Connected to https://github.com/ros2/rosidl/issues/565.
> Expose FastRTPS C typesupport generation via rosidl generate CLI

- fastrtps_cmake_module/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md
- rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
> Updating Quality Declaration

- rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake
- rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
Precisely what the title says. Connected to https://github.com/ros2/rosidl/pull/601.
> Bundle and ensure the exportation of rosidl generated targets

- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
Replace connext with fastrtps in comments.
A simple tech debt payment.
Thanks.
> Replace connext with fastrtps in comments.

- rosidl_typesupport_fastrtps_c/test/test_wstring_conversion.cpp
- rosidl_typesupport_fastrtps_c/test/test_wstring_conversion_mem.cpp
- rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion.cpp
- rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion_mem.cpp
Relates to https://github.com/ament/ament_lint/pull/324
> Fix include order for cpplint

- rosidl_typesupport_fastrtps_c/CMakeLists.txt
- rosidl_typesupport_fastrtps_c/package.xml
- rosidl_typesupport_fastrtps_c/resource/idl__rosidl_typesupport_fastrtps_c.h.em
- rosidl_typesupport_fastrtps_c/resource/idl__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em
- rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/__init__.py
- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/package.xml
- rosidl_typesupport_fastrtps_cpp/resource/idl__rosidl_typesupport_fastrtps_cpp.hpp.em
- rosidl_typesupport_fastrtps_cpp/resource/idl__type_support.cpp.em
- rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em
- rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
- rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/__init__.py
Depends on https://github.com/ros2/rosidl/pull/696
> Replace rosidl_cmake imports with rosidl_pycommon

- rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
- rosidl_typesupport_fastrtps_cpp/package.xml
> Depend on ament_cmake_ros to default SHARED to ON
