ros2/rosidl_typesupport_fastrtps

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_cpp/CMakeLists.txt, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/package.xml
This PR removes what I think is a leftover from copying an existing typesupport that rely on the generation of IDL files and invocation of third party generators.
@MiguelCompany Would you mind having a look and letting us know if this code is necessary ?
First attempt at CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5013)](http://ci.ros2.org/job/ci_linux/5013/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1824)](http://ci.ros2.org/job/ci_linux-aarch64/1824/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4170)](http://ci.ros2.org/job/ci_osx/4170/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5025)](http://ci.ros2.org/job/ci_windows/5 …
=> don't generate IDL files and remove unused code

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
These flags apply to Connext generated code. As we don't generate any code for fastrtps it can be removed.
@MiguelCompany FYI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5026)](http://ci.ros2.org/job/ci_linux/5026/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1834)](http://ci.ros2.org/job/ci_linux-aarch64/1834/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4180)](http://ci.ros2.org/job/ci_osx/4180/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5035)](http://ci.ros2.org/job/ci_windows/5035/)
=> remove more legacy code from Connext typesupport

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
Similar to https://github.com/ros2/rosidl_typesupport_connext/pull/9
Linux build just to make sure it still builds [![Build Status](https://ci.ros2.org/job/ci_linux/5027/badge/icon)](https://ci.ros2.org/job/ci_linux/5027/)
=> avoid using undefined var

rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Closes #3 
Although it is not currently used by downstream packages, this adds the function for consistency across the various type supports for future use
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5028)](http://ci.ros2.org/job/ci_linux/5028/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1835)](http://ci.ros2.org/job/ci_linux-aarch64/1835/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4181)](http://ci.ros2.org/job/ci_osx/4181/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5036)](http://ci.ros2.org/job/ci_windows/5036/)
Connects to #3
=> add specialization of get_service_type_support_handle

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
Fix regression from https://github.com/ros2/rosidl_typesupport_fastrtps/pull/2#discussion_r210142231
The target needs to depend on the actual interface file (in order to re-generate when the input `.msg` / `.srv` file changes) as well as when any of the interface files in the dependency packages have changed.
=> fix the target dependency for automatic regeneration

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/__init__.py, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/__init__.py
Closes #9 
This PR enables us to generate message services from a different directory than `srv`.
Depends on some PRs that are yet pending to be sent against `rosidl`, `rosidl_typesupport` and `rosidl_dds`.
connects to ros2/rosidl#301
=> Enables generation of messages services in an 'action' directory

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
The target dependency won't exist at cmake configure time before the first build if it is generated, so don't `FATAL_ERROR` in that case.
connects to ros2/rcl_interfaces#47
=> Allow generated IDL files

rosidl_typesupport_fastrtps_c/bin/rosidl_typesupport_fastrtps_c, rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/resource/idl__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/idl__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/__init__.py, rosidl_typesupport_fastrtps_cpp/bin/rosidl_typesupport_fastrtps_cpp, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/resource/idl__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/idl__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/__init__.py
=> change generators to IDL-based pipeline

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
Aiming to fix the `rosbag2` `test_cdr_converter` test...
While ROS uses 2 bytes for a U16String FastRTPS operates on `wstring`s and therefore we need to count each character with sizeof(wchar_t)` bytes (instead of 2).
=> fix size calculation for WStrings

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
Fast-CDR is encoding a wchar with a fixed size of four bytes. Hence, in order to stay platform independent, we have to avoid calling `sizeof(wchar_t)`.
https://github.com/eProsima/Fast-CDR/blob/master/src/cpp/FastCdr.cpp#L132
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
=> hard code size of wchar_t to 4

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
The message namespace is to be used by rmw implementations in order to support ROS messages with arbitrary namespaces.
Connects to ros2/ros2#677
=> Add message namespace to type support struct

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
=> code style only: wrap after open parenthesis if not in one line

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/package.xml
Allowing to choose between shared and static libraries.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9335)](http://ci.ros2.org/job/ci_linux/9335/) (same test also failing on master: https://ci.ros2.org/job/ci_linux/9336/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5022)](http://ci.ros2.org/job/ci_linux-aarch64/5022/) (same as Linux)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7642)](http://ci.ros2.org/job/ci_osx/7642/) (it seems the same tests are failing in the nightly - hard to tell with that number though)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9255)](http://ci.ros2.org/job/ci_windows/9255/) (PyQt failures unrelated to …
=> use ament_cmake_ros

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/resource/idl__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/idl__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c/__init__.py, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/resource/idl__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/idl__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/__init__.py
Depends on https://github.com/ros2/rosidl/pull/483.
=> Move headers under detail subfolder and use modern cmake to fix single typesupport builds

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in
Fixes #45.
I have a fix in mind, but let's just get Fbin builds working again (reverting this commit only affects single typesupport builds, which we don't distribute).
=> Revert "Use modern cmake to fix single typesupport builds (#40)"

rosidl_typesupport_fastrtps_c/QUALITY_DECLARATION.md, rosidl_typesupport_fastrtps_cpp/QUALITY_DECLARATION.md
This PR adds a link to REP-2006 (the Security Vulnerability Declaration) to the Quality Declaration for this repository.
Connects to ros2/ros2#924.
=> QD Security Vulnerability Declaration: REP 2006

rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_cpp/package.xml
Removing `exec_dependency` to `rosidl_parser` based on the changes at https://github.com/ros2/ros2/issues/442. Following conversation from https://github.com/ros2/rosidl_typesupport_fastrtps/pull/48#discussion_r456117788. 
Including the `exec_dependency` to `rosidl_runtime_c` does not make any difference when running the building/testing the package locally, not sure if this dependency is already included from other of the dependencies.
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>
=> Update exec dependencies

fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
Follow up of ros2/ros2#943.
Allows plain CMake packages to build while calling `find_package()` something which recursively needs FastRTPS (without manually setting the `CMAKE_PREFIX_PATH` to the `AMENT_PREFIX_PATH`).
@gbiggs @hdino FYI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12673)](http://ci.ros2.org/job/ci_linux/12673/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7636)](http://ci.ros2.org/job/ci_linux-aarch64/7636/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10388)](http://ci.ros2.org/job/ci_osx/10388/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12610)](http://ci.ros2.org/job/ci_windows/12610/)
=> use CMake config dirs as hint for header/library search

rosidl_typesupport_fastrtps_cpp/bin/rosidl_typesupport_fastrtps_cpp, rosidl_typesupport_fastrtps_cpp/package.xml, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/cli.py, rosidl_typesupport_fastrtps_cpp/setup.cfg
Connected to https://github.com/ros2/rosidl_typesupport_fastrtps/pull/65.
=> Expose FastRTPS C++ typesupport generation via rosidl generate CLI

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_c/rosidl_typesupport_fastrtps_c-extras.cmake.in, rosidl_typesupport_fastrtps_cpp/CMakeLists.txt, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/package.xml, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp-extras.cmake.in
This PR updates packages `rosidl_typesupport_fastrtps_c` and `rosidl_typesupport_fastrtps_cpp` to remove their dependency from `fastrtps`, since they only require the `fastcdr` libraries.
This change should allow `rmw_connextdds` (which also relies on these type supports) to avoid an indirect dependency on `fastrtps`.
=> Remove fastrtps dependency

rosidl_typesupport_fastrtps_c/resource/msg__rosidl_typesupport_fastrtps_c.h.em, rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h, rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This extends the initialization callback `max_serialized_size` so it returns whether the type support refers to a POD type.
This change is required in order to support zero-copy on rmw_fastrtps_cpp.
Connects to ros2/rmw_fastrtps#516
Connects to ros2/rmw_connextdds#14
=> Fastdds type support extensions

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_c/test/msg/Test.msg, rosidl_typesupport_fastrtps_c/test/test_cli_extension.py, rosidl_typesupport_fastrtps_cpp/CMakeLists.txt, rosidl_typesupport_fastrtps_cpp/package.xml, rosidl_typesupport_fastrtps_cpp/rosidl_typesupport_fastrtps_cpp/__init__.py, rosidl_typesupport_fastrtps_cpp/test/msg/Test.msg, rosidl_typesupport_fastrtps_cpp/test/test_cli_extension.py
Precisely what the title says. This PR also adds some smoke tests to detect future regression.
CI up to `rosidl_typesupport_fastrtps_c*`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14786)](http://ci.ros2.org/job/ci_linux/14786/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9535)](http://ci.ros2.org/job/ci_linux-aarch64/9535/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12452)](http://ci.ros2.org/job/ci_osx/12452/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14933)](http://ci.ros2.org/job/ci_windows/14933/)
=> Fix Fast-RTPS C++ typesupport CLI extension

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
Precisely what the title says. Should get rid of https://github.com/osrf/infrastructure/issues/5. Follow-up after #73. 
Full CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14942)](http://ci.ros2.org/job/ci_linux/14942/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9684)](http://ci.ros2.org/job/ci_linux-aarch64/9684/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12618)](http://ci.ros2.org/job/ci_osx/12618/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15107)](http://ci.ros2.org/job/ci_windows/15107/) (unrelated warning)
Arguably, quite a few dependencies here should have been `PRIVATE` all along, but (a) that won't spare us …
=> Export rosidl_typesupport_fastrtps_c* dependencies

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This PR fixes a mistake I made on #67, that made bounded sequences be treated as unbounded ones.
The full fix also needs ros2/rmw_fastrtps#540, so that serialization sizes are calculated correctly.
=> Correctly inform that a BoundedSequence is bounded

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
Precisely what the title says. This patch rolls back #73 and #75, as these are incompatible with how ROS 2 binaries are built.
=> Revert rosidl targets and dependencies exportation (#73, #75) 

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/package.xml
Replaces #77 
Alternative to https://github.com/ros2/rosidl/pull/615
Same reasoning as https://github.com/ros2/rosidl_typesupport/pull/118
=> Use FindPython3 explicitly instead of PythonInterp implicitly

rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This PR introduces some minor changes to the C++ message type support templates in order to take advantage of existing functions in Fast CDR for the serialization/deserialization of primitive sequences.
Currently, these are handled via a `for` loop and an element-by-element serialization using the `<<` and `>>` operators. This logic should be improved by the use of `FastCdr::[de]serializeArray()`.
Note that the C message type support already contains these optimizations ([[1]](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/master/rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em#L227), [[2]](https://github.com/ros2/rosidl_typesupport_fastrtps/blob/master/rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em#L372)).
Changes haven't been run through …
=> Improve serialization of primitive bounded sequences in C++ type support

rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This reverts commit b819083079de027f783f389844a949aacfef79cf.
Attempts to address 72 Windows test regressions in the buildfarm.
FYI @asorbini 
I'll wait until I get a CI check that the PR introduces the regressions before removing the draft mode to the PR.
=> Revert "Improve serialization of ... (#79)"

rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This is a follow up to #79, which introduced regressions for `rmw_connextdds` and `rmw_fastrtps`, detected only in Windows Debug builds. Those changes were thus reverted by #80.
This PR proposes the same changes but calls to `[de]serializeArray()` are guarded by a check on the length of the sequence member, which should prevent the previously observed regressions.
Full CI:
- Linux: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15394)](https://ci.ros2.org/job/ci_linux/15394/)
- macOS: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_osx&build=13081)](https://ci.ros2.org/job/ci_osx/13081/)
- Windows (debug): [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15609)](https://ci.ros2.org/job/ci_windows/15609/)
- Windows (release): …
=> Re-introduce improvements to serialization of primitive bounded sequences for C++ type support

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_cpp/CMakeLists.txt
Part of https://github.com/ros2/ros2/issues/1150 - this installs resource_retriever's header files to a unique directory in a merged workspace.
=> Install headers to include/${PROJECT_NAME}

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
Requires #87
Part of ros2/ros2#1150
To be merged at the same time as https://github.com/ros2/rosidl/pull/670
This installs generated headers to a unique include directory to prevent include directory search order issues when overriding packages.
=> Install generated headers to include/${PROJECT_NAME}

rosidl_typesupport_fastrtps_c/package.xml, rosidl_typesupport_fastrtps_c/test/benchmark/benchmark_string_conversions.cpp, rosidl_typesupport_fastrtps_cpp/package.xml, rosidl_typesupport_fastrtps_cpp/test/benchmark/benchmark_string_conversions.cpp
This just quiets a clang static analysis warning.
=> Mark benchmark _ as UNUSED.

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Part of https://github.com/ros2/ros2/issues/1159
Depends on https://github.com/ros2/rosidl/pull/722
Make the codegen type hash available to typesupport struct for distribution during discovery. See https://github.com/ros2/rmw_fastrtps/pull/671 for usage
=> Expose type hash to typesupport structs (rep2011)

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/service_type_support.h, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Depends on ros2/rosidl#729 (coupled - must be merged together)
Part of ros2/ros2#1159
1. Fill out new type_hash and message_type_support fields on generated `rosidl_message_type_support_t` and `rosidl_service_type_support_t` structs.
2. Back out addition of the type hash to the typesupport-implementation data bundles
=> Type hashes on typesupport (rep2011)

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/resource/srv__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/package.xml, rosidl_typesupport_fastrtps_cpp/resource/idl__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Part of ros2/ros2#1159
Depends on https://github.com/ros2/rosidl/pull/727 (and is bundled with)
=> Type Description Nested Support

rosidl_typesupport_fastrtps_cpp/resource/srv__type_support.cpp.em
Service's Event message doesn't exist in Humble, so we don't need this block
Merges into https://github.com/ros2/rosidl_typesupport_fastrtps/pull/104
=> PR 104 (backport 102->humble) Resolve merge conflict

rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em
This shall address https://github.com/ros2/rmw_fastrtps/issues/715 by taking into consideration whether the alignment generated by the compiler is compatible with the one required by the CDR serialization.
=> Account for alignment on `is_plain` calculations

rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake, rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake
The comment in the commit explains the reasoning behind it.
This must be merged before https://github.com/ros2/ros2/pull/1524 ; see that pull request for more information about this change.
=> Set hints to find the python version we actually want.

rosidl_typesupport_fastrtps_c/CMakeLists.txt, rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/serialization_helpers.hpp, rosidl_typesupport_fastrtps_c/include/rosidl_typesupport_fastrtps_c/wstring_conversion.hpp, rosidl_typesupport_fastrtps_c/resource/msg__type_support_c.cpp.em, rosidl_typesupport_fastrtps_c/test/benchmark/benchmark_string_conversions.cpp, rosidl_typesupport_fastrtps_c/test/test_wstring_conversion.cpp, rosidl_typesupport_fastrtps_c/test/test_wstring_conversion_mem.cpp, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/serialization_helpers.hpp, rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/wstring_conversion.hpp, rosidl_typesupport_fastrtps_cpp/resource/msg__type_support.cpp.em, rosidl_typesupport_fastrtps_cpp/test/benchmark/benchmark_string_conversions.cpp, rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion.cpp, rosidl_typesupport_fastrtps_cpp/test/test_wstring_conversion_mem.cpp
This PR changes (de)serialization of wide strings so they don't perform `u16string` <-> `wstring` conversions
=> Improve wide string (de)serialization

rosidl_typesupport_fastrtps_cpp/include/rosidl_typesupport_fastrtps_cpp/message_type_support.h, rosidl_typesupport_fastrtps_cpp/resource/msg__rosidl_typesupport_fastrtps_cpp.hpp.em
Bug introduced in ros2/rosidl_typesupport_fastrtps#116
This specifically generated cpplint warnings on generated services (for example https://ci.ros2.org/job/ci_linux/20791/#showFailuresLink)
=> Fix how header template works to prevent double-inclusion
